proposals/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', list_proposal_types, name='proposal_types'),
    path('<str:proposal_type>/new', ProposalEditView.as_view(), name='new_proposal'),
    path('<str:proposal_type>/edit/<int:proposal_id>', ProposalEditView.as_view(), name='edit_proposal'),
    path('<str:proposal_type>/<int:proposal_id>', ProposalView.as_view(), name='view_proposal'),
    path('<str:proposal_type>/<int:proposal_id>/comment/new', post_comments, name='post_comment'),
    path('<str:proposal_type>', ProposalListView.as_view(), name='proposal_type'),
]

teconf/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import signup, home, logout_user
# import proposals.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('signup/', signup, name='signup'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', logout_user, name='logout_user'),
    path('auth/', include('social_django.urls', namespace='social')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', home, name='home'),
    path('proposals/', include(('proposals.urls', 'proposals'), namespace='proposals-types')),
    path('tinymce/', include('tinymce.urls')),
]

proposals/models.py
from django.db import models
from tinymce.models import HTMLField
from datetime import datetime
from django.contrib.auth.models import User
# from conference import Conference

# Create your models here.

PROPOSAL_TYPES = [
    ('talk', 'Talk'),
    ('workshop', 'Workshop')
]


class Proposals(models.Model):

    title = models.CharField(max_length=250)
    description = HTMLField()
    audience = models.CharField(max_length=1500)
    status = models.CharField(max_length=50)
    proposal_type = models.CharField(choices=PROPOSAL_TYPES, max_length=25)
    proposal_section = models.CharField(max_length=1500)
    pre_requisites = HTMLField()
    current_urls = HTMLField()
    speaker_info = HTMLField()
    speaker_links = HTMLField()
    created_date = models.DateTimeField(default=datetime.now())
    updated_date = models.DateTimeField(default=datetime.now())
    author_id = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    comments_count = models.IntegerField(default=0)


class Comment(models.Model):
    proposal = models.ForeignKey(Proposals, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    text = HTMLField()
    created_date = models.DateTimeField(default=datetime.now())
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.text

proposals/forms.py
from django import forms
from .models import Proposals
# from markedit.widgets import MarkEdit


class ProposalForm(forms.ModelForm):

    class Meta:
        model = Proposals

        fields = [
            "id",
            "title",
            "description",
            "audience",
            "status",
            "proposal_type",
            "proposal_section",
            "pre_requisites",
            "current_urls",
            "speaker_info",
            "speaker_links",
        ]

        # widgets = {
        #     "description": MarkEdit()
        # }

proposals/views.py
from django.shortcuts import render, redirect
from .forms import *
from .models import PROPOSAL_TYPES, Proposals, Comment
from django.views.generic.edit import FormView
from django.views.generic.base import TemplateView
from datetime import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse


def generate_prposal_type_url(p_type):
    return '{}'.format(p_type)


def list_proposal_types(request):
    proposal_types = []
    for p_type in PROPOSAL_TYPES:
        proposal_types.append({
            'p_type': p_type[0],
            'p_type_url': generate_prposal_type_url(p_type[0])
        })
    return render(request, 'proposal_type.html', {'proposal_types': proposal_types})


class ProposalListView(FormView):

    def get(self, request, proposal_type=None):
        data = {
            'proposal_type': proposal_type,
            'proposals': []
        }
        data['proposals'] = Proposals.objects.filter(proposal_type=proposal_type)
        return render(request, 'proposal_list.html', {'data': data})


class ProposalView(TemplateView):

    form_class = ProposalForm

    def get(self, request, *args, **kwargs):
        proposal_id = kwargs.get('proposal_id', None)
        proposal_type = kwargs.get('proposal_type', None)
        bread_crumbs = []
        comments = []
        editable = False
        if proposal_type:
            bread_crumbs.append({'url': '/' + proposal_type, 'label': dict(PROPOSAL_TYPES)[proposal_type]})
        if proposal_id is not None:
            proposal = Proposals.objects.get(id=proposal_id)
            comments = Comment.objects.filter(proposal=proposal_id)
            bread_crumbs.append({'url': proposal.id, 'label': proposal.title})
            editable = True if (proposal.author_id == request.user) else False
            # proposal_form = self.form_class(instance=proposal)
        else:
            bread_crumbs.append({'url': 'new_proposal', 'label': 'New'})
        return render(request, 'proposal_view.html', {'proposal': proposal, 'bread_crumbs': bread_crumbs, 'editable': editable, 'comments': comments})


class ProposalEditView(TemplateView):
    form_class = ProposalForm
    redirect_field_name = "/proposals/"

    def get(self, request, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseRedirect(reverse('login'))
        proposal_id = kwargs.get('proposal_id', None)
        proposal_type = kwargs.get('proposal_type', None)
        bread_crumbs = []
        if proposal_type:
            bread_crumbs.append({'url': '/' + proposal_type,'label': dict(PROPOSAL_TYPES)[proposal_type]})
        if proposal_id is not None:
            proposal = Proposals.objects.get(id=proposal_id)
            bread_crumbs.append({'url': proposal.id, 'label': proposal.title})
            proposal_form = self.form_class(instance=proposal)
        else:
            bread_crumbs.append({'url': 'new_proposal', 'label': 'New'})
            proposal_form = self.form_class()
        return render(request, 'proposal_create.html', {'form': proposal_form, 'bread_crumbs': bread_crumbs})

    def post(self, request, *args, **kwargs):
        proposal_form = self.form_class(request.POST)

        data = {'proposal_type': 'talk',
                'proposals': Proposals.objects.all()}
        bread_crumbs = []
        if proposal_form.is_valid():
            if request.POST.get('proposal_id', None) and (request.POST.get('proposal_id') != 'None'):
                proposal = Proposals.objects.get(id=request.POST.get('proposal_id'))
                self.form_class(request.POST, instance=proposal).save(commit=False)
                proposal.updated_date = datetime.now()
            else:
                proposal = proposal_form.save(commit=False)
                proposal.author_id = request.user
            proposal.save()
            bread_crumbs = [{'url': proposal.proposal_type, 'label': dict(PROPOSAL_TYPES)[proposal.proposal_type]},
                            {'url': proposal.id, 'label': proposal.title}]
            data = {
                'proposal_type': proposal.proposal_type,
                'proposals': Proposals.objects.all(),
            }
        return render(request, 'proposal_list.html', {'data': data, 'bread_crumbs': bread_crumbs})


def post_comments(request, proposal_type, proposal_id):
    proposal = Proposals.objects.get(id=proposal_id)
    text = request.POST.get('text')
    comment = Comment(proposal=proposal, author=request.user, text=text)
    comment.save()
    proposal.comments_count += 1
    proposal.save()
    return redirect('/proposals/'+proposal_type + '/' + str(proposal_id))

proposals/templates/proposal_create.html
{% extends 'base.html' %}

{% block content %}
    <div class="col-lg-12">

        <div class="col-md-10 col-md-offset-1">
            <div class="row">
                <div class="col-sm-12">
                    {{ form.media }}
                    {% if form.instance.id is undefined %}<h2>New Proposal</h2>{% endif %}
                    <hr/>
                    <div class="form-container space-2-bottom">
                        <form name="Proposal" id="new_or_edit_proposal" enctype="multipart/form-data" method="post" action="{{ request.get_full_path }}">
                            {% csrf_token %}
                            <input type="hidden" name="proposal_id" value="{{ form.instance.id }}">
                            {{ form.as_p }}
                            <div class="modal-footer">
                                    <button type="submit" id="confirm_ok" class="btn btn-success">Ok</button>
                                    <button type="button" id="confirm_discard" class="btn btn-default">Discard</button>
                                  </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

    </div>
    <!--<div class="col-lg-12">-->
        <!--<form name="quiz" id="new_proposal" enctype="multipart/form-data" method="POST" action="{{ request.get_full_path }}">{% csrf_token %}-->
            <!--<div class="row">-->
                <!--<div class="col-lg-12">-->
                    <!--<div class="app-create-block">-->
                        <!--<div class="clearfix">-->
                            <!--<div class="col-lg-6 col-sm-6 col-xs-12 mt-10">-->
                                <!--<div class="gen_test-wrap">-->
                                    <!--<label >{{ form.proposal.title.label }}<span style="color:#ff0000;"> *</span></label>-->
                                        <!--{{ form.proposal.title }}-->

                                        <!--<p class="hint-txt">{{ form.proposal.title.help_text }}</p>-->


                                        <!--<span class="help-inline" style="color:red;">{{ form.proposal.title.errors }}</span>-->
                                <!--</div>-->
                             <!--</div>-->
                             <!--<div class="col-lg-6 col-sm-6 col-xs-12 mt-10">-->
                                <!--<div class="gen_test-wrap">-->
                                    <!--<label>{{ form.proposal.description }}</label>-->

                                    <!--<textarea style="display: none;" style="display: none;">{{ form.proposal.description }}</textarea>-->
                                    <!--<p class="hint-txt">{{ forms.quiz.language.help_text}}</p>-->

                                    <!--<span class="help-inline" style="color:red;">{{ forms.quiz.language.errors }}</span>-->
                                <!--</div>-->
                            <!--</div>-->
                        <!--</div>-->

                    <!--</div>-->
                <!--</div>-->
            <!--</div>-->
        <!--</form>-->
<!--</div>-->

{% endblock %}

proposals/templates/proposal_list.html
{% extends 'base.html' %}

{% block content %}



    <div class="container-fluid" role="main">
        <div class="row-fluid clearfix">
            <div class="col-md-10 col-md-offset-1">

                <section class="content custom-container proposal-list">
                    <div class="push-4-bottom push-1-top">
                        <div class="row">
                            <div class="col-xs -12 col-sm-12 ">

                                        <p class="text-left"></p>
                                        <h1>Proposals</h1>

                                        <p>Posters are graphical summary of projects or ideas. They are usually presented with an A0 size poster, but any creative ways are always welcome. The poster session provides an opportunity to network with the conference attendees and acts as a starting point for further discussions. While talks generally needs to appeal to a wide section of the community, posters can cover niche topics.   </p>
                                        <p>PyCon India 2019 will be having a poster presentation session at post lunch, day 1. During the poster presentation session you will be provided with a poster board that can hold an A0 size poster, and a table to place your laptop, for demos. Conference attendees interested in your topic, will stop by, during which you can give them a brief presentation / demo.  </p>
                                        <h2>Timeline</h2>
                                        <ul>
                                        <li>Poster CFP opens: 3rd June, 2019  </li>
                                        <li>Poster CFP closes: 31 August, 2019  </li>
                                        <li>Selected posters announced: 14th September, 2019  </li>
                                        <li>Draft posters to be submitted On: 15th September, 2019  </li>
                                        <li>Posters will be presented on: 12th October, 2019  </li>
                                        </ul>
                                        <h2>FAQ</h2>
                                        <h3>What is the difference between a talk and a poster?</h3>
                                        <p>Talks and posters are different ways of interacting with the conference audience. A topic can be presented as talk, if the intention is to explain the topic in detail. A poster on the other hand, is similar to a lightning talk, in that it quickly introduces the audience to a topic, and acts as trigger point for further discussion.  </p>
                                        <p>There are some specific cases where posters are better suited than talks:  </p>
                                        <ul>
                                        <li>
                                        <p>Due to the nature of the poster presentation format, it is better suited for demos, the attendees can interact with the project. This is especially useful for hardware projects.  </p>
                                        </li>
                                        <li>
                                        <p>If you are first time conference attendee, or a first time speaker at a conference, posters let you engage with the audience without getting intimidated by the large crowd.  </p>
                                        </li>
                                        <li>
                                        <p>Niche topics that are domain heavy, are better suited as posters. Examples: Python in local language computing, Python in embedded Linux build automation, Python used in scientific study of ailments, etc.  </p>
                                        </li>
                                        </ul>
                                        <h3>Can I submit both a talk and a poster proposal?</h3>
                                        <p>You can submit a talk and poster proposal for the same topic. If your talk does not get selected, you can use the poster session, to introduce your topic, and engage with the audience. Given the limited space and time at the conference, only one of them will get selected though.  </p>
                                        <h3>What makes a good poster?</h3>
                                        <p>First, ensure that you select a good title. Conference attendees will use it to determine which posters to attend. Make sure it brings in audience who will be interested in your poster.   </p>
                                        <p>Second, for the poster itself, here are a few tips for creating the poster:  </p>
                                        <ul>
                                        <li>While textual representation is good, graphical representation will attract more eyes  </li>
                                        <li>Make sure the contents are properly sized and spaced in the poster so that it is viewable from decent distance  </li>
                                        <li>Provoke the reader's curiosity which will open up space for further discussions  </li>
                                        <li>Provide links for the attendees to know more about the topic and connect with you / the community  </li>
                                        </ul>
                                        <h3>Do you have sample poster proposals to get started?</h3>
                                        <p>You can check the poster proposals from other conferences:  </p>
                                        <ul>
                                        <li><a href="https://pysangamam.org/blog/2018/08/29/announcing-selected-posters/">PySangamam 2018</a></li>
                                        <li><a href="https://us.pycon.org/2019/schedule/posters/list/">PyCon US 2019</a></li>
                                        </ul>
                                        <h3>Can I do a poster in a local language?</h3>
                                        <p>Yes! Since attendees can choose which poster they want to attend, your poster can be in a local language. This makes sense only if there will be sufficient no. of participants who are familiar with the language. This can also be done, if the topic is itself about projects / libraries on regional language computing. Please be noted that the proposal itself needs to be in English, for the reviewers to be able to comprehend your proposal.  </p>
                                        <h2>Questions and Discussions</h2>
                                        <p>Contact the coordinators through email:<br>
                                        Naren - narenravi92@gmail.com <br>
                                        Abhishek - zerothabhishek@gmail.com<br>
                                        The team: cfp@in.pycon.org</p><p></p>



                            </div>
                        </div>

                        <hr>
                        <a name="proposals"></a>
                        <div class="row">
                            <a class="btn btn-primary pull-right" href="{% url 'proposals:new_proposal' data.proposal_type %}">
                                <i class="fa fa-plus-square-o"></i> New Proposal
                            </a>

                        </div>
                        <h2 class="section-title">List of Proposals</h2>

                        {% for proposal in data.proposals %}
                        <hr/>
                        <div class="row user-proposals">
                            <div class="col-xs-12">
                                <div class="proposal-list-content">
                                  <div class="col-sm-1 hidden-xs proposal-stats">

                                        <div class="text-center space-on-top">
                                            <i class="fa fa-comments-o"></i>
                                            <span class="align-middle">
                                                {{ proposal.comments_count }}
                                            </span>
                                        </div>
                                    </div>
                                    <div class="col-sm-11 col-xs-12">
                                        <p class="col-xs-12  visible-xs">
                                            <span class="pull-left">
                                                <i class="fa fa-comments"></i>2
                                            </span>
                                            <span class="pull-right">
                                                <i class="fa fa-thumbs-up"></i>0
                                            </span>
                                        </p>
                                        <h3 class="proposal--title">
                                            <a href="{% url 'proposals:view_proposal' proposal.proposal_type proposal.id %}">{{ forloop.counter }}. {{ proposal.title }}</a>
                                        </h3>
                                        <div class="clearfix">
                                            <div class="pull-left">

                                                <span></span>
                                                <a class="tag tag__proposal_type label label-proposal-type inline-block" href="?proposal_type=19#proposals">{{ proposal.proposal_type }}
                                                </a>

                                                <a class="tag tag__proposal_section label label-proposal-type inline-block" href="?proposal_section=95#proposals">{{ proposal.proposal_section }}
                                                </a>
                                            </div>

                                            <small class="pull-right">
                                                <i class="fa fa-user"></i><b>{{ proposal.author_id }}</b> |&nbsp;
                                                <i class="fa fa-calendar"></i> <b title="11 Jun 2019, 22:36">{{ proposal.created_date }}</b>
                                            </small>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}

                    </div>
                </section>

            </div>
        </div>
    </div>


{% endblock %}

proposals/templates/proposal_type.html
{% extends 'base.html' %}

{% block content %}
    <main role="main" id="main-content" tabindex="-1">
        <div class="blog">
            <h1><strong>Submit a Proposal</strong></h1>
            <div class="container">
                {% for p_type in proposal_types %}
                <div class="row">
                    <div class="col-md-6 light">
                        <h3 class="text-uppercase"><strong>{{ p_type.p_type }}</strong></h3>
                    </div>
                    <div class="col-md-6 light">
                        <div class="buy-ticket">
                            <a href="{{ p_type.p_type_url }}" class="dwd-link text-uppercase"><strong>SUBMIT A {{ p_type.p_type }}</strong></a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>

        </div>
    </main>
{% endblock %}