proposals/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', list_proposal_types, name='proposal_types'),
    path('<str:proposal_type>/new', ProposalEditView.as_view(), name='new_proposal'),
    path('<str:proposal_type>/edit/<int:proposal_id>', ProposalEditView.as_view(), name='edit_proposal'),
    path('<str:proposal_type>/<int:proposal_id>', ProposalView.as_view(), name='view_proposal'),
    path('<str:proposal_type>/<int:proposal_id>/comment/new', post_comments, name='post_comment'),
    path('<str:proposal_type>', ProposalListView.as_view(), name='proposal_type'),
]

teconf/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import signup, home, logout_user
# import proposals.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('signup/', signup, name='signup'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', logout_user, name='logout_user'),
    path('auth/', include('social_django.urls', namespace='social')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', home, name='home'),
    path('proposals/', include(('proposals.urls', 'proposals'), namespace='proposals-types')),
    path('tinymce/', include('tinymce.urls')),
]

templates/account_activation_email.html
{% autoescape off %}
Hi {{ user.username }},

Please click on the link below to confirm your registration:

<!--http://{{ domain }}{% url 'activate' uidb64=uid token=token %}-->
{% endautoescape %}

templates/base.html
{% load static %}
<html>
    <head>
        <title>TeConf</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <!--<link rel="stylesheet" href="{% static 'css/blog.css' %}">-->
    </head>
    <body>
        <div class="page-header">
            <h1><a href="/">TeConf</a></h1>
            {% if user.is_authenticated %}
             <p class="display-4">Hello, {{ user.username }}</p>
             <a class="lead" href="{% url 'logout_user' %}">Logout</a></p>
	{% else %}
             <a class="lead" href="{% url 'login' %}">Log in</a>
	{% endif %}
        </div>

        <div class="content container">
            <div class="row">
                <div class="col-md-8">
                {% block content %}
                {% endblock %}
                </div>
            </div>
        </div>
    </body>
</html>

templates/home.html
{% extends "base.html" %}

{% block content %}
	{% if user.is_authenticated %}
             <p class="display-4">Hello, {{ user.username }}</p>
			 <a class="lead" href="{% url 'proposals:proposal_types' %}">Submit A Proposal</a>
	{% else %}
             <a class="lead" href="{% url 'login' %}">Log in</a>/<a class="lead" href="{% url 'signup' %}">Signup</a>
	{% endif %}
{% endblock content %}

templates/signup.html
{% extends 'base.html' %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}